### ISSUE TITLE
Fail in XML roundtrip

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/xml-component#1]
A user was trying a scenario where an XML component was used to convert one JSON file and then right after that the same XML was converted into JSON. The process failed with an error like:
```js
Error: Unencoded <
Line: 13
Column: 10
Char: 3
    at error (/app/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/app/node_modules/sax/lib/sax.js:693:7)
    at SAXParser.write (/app/node_modules/sax/lib/sax.js:1096:13)
    at Parser.exports.Parser.Parser.parseString (/app/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/app/node_modules/xml2js/lib/xml2js.js:7:59)
    at TaskExec.processAction (/app/lib/actions/xmlToJson.js:28:12)
    at Promise (/app/node_modules/elasticio-sailor-nodejs/lib/executor.js:20:58)
    at TaskExec.process (/app/node_modules/elasticio-sailor-nodejs/lib/executor.js:19:5)
    at processMessageWithModule (/app/node_modules/elasticio-sailor-nodejs/lib/sailor.js:215:22)
    at Sailor.doProcess (/app/node_modules/elasticio-sailor-nodejs/lib/sailor.js:186:20)
    at doProcess.next (<anonymous>)
    at onFulfilled (/app/node_modules/co/index.js:65:19)
    at _fulfilled (/app/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/app/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/app/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:796:13)
    at /app/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:857:14
```

To reproduce do the following steps:

1. Use REST API component to `GET` the JSON from here `https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.13/dist.json`
2. Pass the received JSON to XML component and do `JSON to XML` action
3. Pass the received XML to XML component and do `XML to JSON` action.
4. Get the error

**Comment by HannaTrotsenko** [comment]
- [ ] bug
@Nazar910  can't copy w3school url with mouth. not good UX
- [ ] QA

**Comment by Nazar910** [comment]
@HannaTrotsenko you can copy it from the console :)

**Comment by HannaTrotsenko** [comment]
I'm omnipotent!!! :+1: )))))))))

**Comment by HannaTrotsenko** [comment]
Functional testing is passed
